### ISSUE TITLE
erkale_bastool doesn't have a suffix in the pareallel build

### ISSUE THREAD

**Issue by yurivict** [susilehtola/erkale#30]
Other executables have the suffix ```_omp```.

**Comment by susilehtola** [comment]
Not a bug, this is by design. Basis set tool barely has any parallel sections.

**Comment by yurivict** [comment]
From the packaging point of view, it is easier to have 2 completely different sets of files and have 2 packages: sequential and parallel. It's nicer if they don't depend on each other for just one executable and the headers.

**Comment by susilehtola** [comment]
You can put both versions in the same package.

Or edit the CMake files yourself and add the suffix.
