### ISSUE TITLE
Computation results are printed to the standard output

### ISSUE THREAD

**Issue by yurivict** [susilehtola/erkale#44]
For example, this computation
```
System M.xyz
Method lda_x-lda_c_vwn
Basis 3-21G
```
prints the results to ```stderr```.

Please consider changing this and printing results to ```stdout```, because ```stderr``` is usually reserved for errors. Please note that some software (ex. ASE) parses results of external processes. They would also probably expect them on ```stdout```.

**Comment by susilehtola** [comment]
This is again a design decision made in the initial design of the program. Stdout is by default redirected to a log file, so that the program outputs sparsely to stderr.
