### ISSUE TITLE
[questions]

### ISSUE THREAD

**Issue by yurivict** [susilehtola/erkale#48]
I have two questions:
* How to set precision with which it computes energy and optimizes? Supposedly, lowering precision should make it run faster.
* How to optimize a molecule while leaving some parts fixed? For example, if the molecule consists of two parts that are linked with each other with several bonds, I would like to fix the shapes of these parts individually, and only optimize over how parts are located/rotated relative to each other.

Additionally, the user guide pdf URL seems to be dead: http://theory.physics.helsinki.fi/~jzlehtol/erkale/doc/userguide.pdf
It resolves to the IP address, but can't be connected to.

Thank you,
Yuri

**Comment by susilehtola** [comment]
On 2/7/19 11:30 AM, yuri@FreeBSD wrote:
> I have two questions:
> 
>   * How to set precision with which it computes energy and optimizes?
>     Supposedly, lowering precision should make it run faster.

The SCF convergence threshold is set by ConvThr, see manual.

>   * How to optimize a molecule while leaving some parts fixed? For
>     example, if the molecule consists of two parts that are linked with
>     each other with several bonds, I would like to fix the shapes of
>     these parts individually, and only optimize over how parts are
>     located/rotated relative to each other.

The geometry optimizer is very simple. The only option that exists is to 
fix individual atoms. You do this by adding the -Fx suffix for the atom 
in the xyz file.

> Additionally, the user guide pdf URL seems to be dead: 
> http://theory.physics.helsinki.fi/~jzlehtol/erkale/doc/userguide.pdf
> It resolves to the IP address, but can't be connected to.

Which URL? The one in the repo README works.
-- 
------------------------------------------------------------------
Mr. Susi Lehtola, PhD             Junior Fellow, Adjunct Professor
susi.lehtola@alumni.helsinki.fi   University of Helsinki
http://susilehtola.github.io/     Finland
------------------------------------------------------------------
Susi Lehtola, dosentti, FT        tutkijatohtori
susi.lehtola@alumni.helsinki.fi   Helsingin yliopisto
http://susilehtola.github.io/
------------------------------------------------------------------

**Comment by yurivict** [comment]
Is there a way to also compute per-nuclei forces or energy gradients in addition to the energy itself?

**Comment by susilehtola** [comment]
That's already done by the geometry optimizer.

**Comment by yurivict** [comment]
> That's already done by the geometry optimizer.

What if I don't need geometry optimization? I have an unoptimized molecule with some internal forces acting between atoms. Can I compute just these forces?

Being able to compute such forces can allow to model the motion of atoms, step by step.

**Comment by susilehtola** [comment]
You mean run molecular dynamics? Sure, why not: forces are implemented. Hack the code as you want. But there are other programs that are designed to do this quicker. Like CP2K.
