### ISSUE TITLE
The manual doesn't really explain how to visualize orbitals in Avogadro

### ISSUE THREAD

**Issue by yurivict** [susilehtola/erkale#49]
Section ```5.5 Visualization of orbitals and densities``` just says to set resolution to "High", but it doesn't say which file to open, which command line to run. Avogadro certainly doesn't know how to open .chk files.

Also please note that old Avogadro is now obsolete (it also used EOLed Qt4). Avogadro is now called ```Avogadro2```, and is now at version ```1.91.0```.

**Comment by susilehtola** [comment]
Documented better in 4653fa3.
