### ISSUE TITLE
How to compile the contrib code in erkale?

### ISSUE THREAD

**Issue by chrinide** [susilehtola/erkale#52]
Hi Susi Lehtola,

I have tried to compile the contrib code in erkale src/contrib, but many times, I failed.

Could you please kindly give some guide?

**Comment by susilehtola** [comment]
I have compiled the contrib code succesfully many times. It's not compiled by default since it's not supported. The procedure should be quite simple, just uncomment the `add_subdirectory(contrib)` line in `CMakeLists.txt`.

**Comment by chrinide** [comment]
Thanks very much,  Susi Lehtola.

I got the point and succesfully compiled them.
