### ISSUE TITLE
Why is energy computation in Erkale slower than in NWChem?

### ISSUE THREAD

**Issue by yurivict** [susilehtola/erkale#58]
Hello Susi Lehtola,

I am running this butane molecule rendering:
```
14
butane molecule
C 0.897383979232888 0.00104934693693011 -0.0582316457839244
C 2.41638544401567 -0.00922660136992455 -0.0507791957047302
C 2.96079728106612 -1.17616227349055 0.77079794112017
C 4.48027302369498 -1.18518648308844 0.779573215262362
H 0.525637143788597 0.842641408772114 -0.650785369789418
H 0.501265337011072 0.0995117030651041 0.957919910000232
H 0.501375586027604 -0.922462495067919 -0.493273203845744
H 2.78186722984511 0.938938066822998 0.36068152249494
H 2.78197786220054 -0.0770827655800536 -1.08221390950194
H 2.59634214172523 -2.12423990068662 0.358328954782226
H 2.59412891348885 -1.10892707797308 1.80179215266436
H 4.87671074108315 -1.28264172787112 -0.236077862188468
H 4.85147342082677 -2.02700354596779 1.37225561912063
H 4.87438913424773 -0.261669098762196 1.21548291246125
```

through Erkale and NWChem.

The Erkale script is:
```
System butane.xyz
Method lda_x-lda_c_vwn
Basis 3-21G
ConvThr 0.01
SaveChk lda.chk
```

The NWChem script is:
```
title "butane"
echo
geometry units angstroms
 load butane.xyz
 symmetry c1
end
basis
 C library 3-21G
 H library 3-21G
end
scf
  thresh 0.01
end
task scf energy
```

The energies returned by NWChem and Erkale are comparable: -156.07188541 and -156.430937088360 respectively.

But the computation times of NWChem and Erkale are different:
wallclock time: 1.25s and 2.40s respectively
user time: 5.80s and 17.5s respectively

Erkale is parallelized through multithreading/OpenMP on 8 threads/CPUs.
NWChem parallelizes through MPI/MPICH on 8 processes/CPUs.

The question is why is Erkale slower? Is this comparison valid?

**Comment by susilehtola** [comment]
https://aip.scitation.org/doi/10.1063/5.0004997 vs https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.22987
