### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by lucamontana** [susilehtola/erkale#6]
when compiling erkale, the only thing you get is error and error and error.
This is great. I love it.

**Comment by lucamontana** [comment]
A further question :   

can erkale restricted open shell TD-DFT ? 

LUCA

**Comment by susilehtola** [comment]
I don't seem to get automatic emails for the issues, so I didn't see this until now.

You have not documented anything about your issue. If you're running Red Hat / Fedora, please use the precompiled packages which are trivial to install.
