### ISSUE TITLE
Realtivistic Hamiltonians in Erkale?

### ISSUE THREAD

**Issue by chrinide** [susilehtola/erkale#61]
Dear Susi Lehtola,

Thanks so much for your great and unique Erkale code. Recently we would like to do a relativistic EMD calculations, however, there is only Erkale can do non-relativistic EMD. (A wrong operation )in my old post closed https://github.com/susilehtola/erkale/issues/60)

So I would like to know is there any possibility to implement any Relativistic Hamiltonians(Just like the simplest ZORA, or the famous X2C) in Erkale?

**Comment by susilehtola** [comment]
You can run the relativistic calculations in another program like Gaussian or Psi4, and read in the formatted checkpoint files into ERKALE as instructed in the users' manual.
