### ISSUE TITLE
Misprint in compile.sh

### ISSUE THREAD

**Issue by vladislavivanistsev** [susilehtola/erkale#7]
In 

> wget -O cmake-${CMAKEVER}.tar.gz http://www.cmake.org/files/v3.4/cmake-${CMAKEVER}.tar.gz

should be v3.7 instead of v3.4

like this

> wget -O cmake-${CMAKEVER}.tar.gz http://www.cmake.org/files/v3.7/cmake-${CMAKEVER}.tar.gz

**Comment by susilehtola** [comment]
Thanks for the report! Sorry, I don't seem to get automatic emails for the issues. This is now fixed using a substring technique, so it shouldn't happen again.
