### ISSUE TITLE
Can Erkale compute in sutuations when free electrons/ions are involved ?

### ISSUE THREAD

**Issue by yurivict** [susilehtola/erkale#75]
For example in these situations:
* a fast-moving electron hits the atom and causes an ionization event: Molecule+e⁻→Ion⁺+e⁻+e⁻
* a fast moving hydrogen atom causes an ionization event: Molecule+H→Ion⁺+H+e⁻

The manual says that Erkale can compute X-ray interactions, but it doesn't mention free electron interaction.

**Comment by susilehtola** [comment]
I am not familiar with these processes. How is the scattering section calculated in other codes?

An issue with describing free electrons is that Gaussian basis sets tend not be very accurate; I have seen many works where the continuum is modeled using a real space approach.

ERKALE is basically in maintenance mode; I am not adding new features anymore as faster and more modern alternatives have become available.

**Comment by susilehtola** [comment]
For X-ray absorption spectroscopies, [PsiXas](https://github.com/Masterluke87/psixas/) is a fresh reimplementation of the transition potential approximation as a add-on module to Psi4.

**Comment by yurivict** [comment]
Thank you for this information, Susi.

**Comment by yurivict** [comment]
> How is the scattering section calculated in other codes?

Answering your question: I'm not sure how is it computed, but there is a code called ePolyScat that computes cross-sections of electron/molecule interactions: https://amosgateway.org/eps/

Yuri
