### ISSUE TITLE
Confusion about SAP as initial guess

### ISSUE THREAD

**Issue by FreemanTheMaverick** [susilehtola/erkale#88]
Hi!

I have read the article "Assessment of Initial Guesses for Self-Consistent Field Calculations. Superposition of Atomic Potentials: Simple yet Efficient" and think of the SAP as a brilliant idea as initial guess for SCF. But a little confusion is troubling me:

The Fock matrix is written as:
$F_{pq}=h_{pq}+\sum_{r,s}P_{rs}(pr|qs)+(V_{XC})_{pq}$
As far as I know, SAP accounts for the V_XC term, but what about the second term where there has to be a density matrix? How do SAP provide a guess of the second term in practice?

I would appreciate it if you could help me with this. Thank you!

**Comment by susilehtola** [comment]
As discussed in [J. Chem. Theory Comput. 15, 1593 (2019)](https://doi.org/10.1021/acs.jctc.8b01089), SAP includes both density dependent terms: both Coulomb and exchange/exchange-correlation.

We have also formulated a more efficient version of the guess for Gaussian-basis calculations in [J. Chem. Phys. 152, 144105 (2020)](https://doi.org/10.1063/5.0004046). This is available in ERKALE with the `guess sapfit` keyword.

**Comment by FreemanTheMaverick** [comment]
> As discussed in [J. Chem. Theory Comput. 15, 1593 (2019)](https://doi.org/10.1021/acs.jctc.8b01089), SAP includes both density dependent terms: both Coulomb and exchange/exchange-correlation.
> 
> We have also formulated a more efficient version of the guess for Gaussian-basis calculations in [J. Chem. Phys. 152, 144105 (2020)](https://doi.org/10.1063/5.0004046). This is available in ERKALE with the `guess sapfit` keyword.

Thank you. Do you mean that the initial guess should be obtained with $F_{pq}^\mathrm{initial}=h_{pq}+V^\mathrm{SAP}_{pq}$ where $V^\mathrm{SAP}_{pq}$ is given by eq.-17 of https://doi.org/10.1021/acs.jctc.8b01089 ?

**Comment by FreemanTheMaverick** [comment]
> > Thank you. Do you mean that the initial guess should be obtained with
> > Fpqinitial=hpq+VpqSAP
> > where VpqSAP is given by eq.17 of https://doi.org/10.1021/acs.jctc.8b01089 ?
> 
> Exactly.
> 
> You can also combine VSAP with the bare nuclear potential, which yields something that becomes zero at long range: VSAP→Z/r for r→∞.

Thank you! Now I know more about SAP.
