### ISSUE TITLE
Unitary optimized PM localization on largely conjugated systems

### ISSUE THREAD

**Issue by FreemanTheMaverick** [susilehtola/erkale#91]
Hi.

I wonder if there is any follow-up research on unitary optimized orbital localization, introduced in https://pubs.acs.org/doi/10.1021/ct400793q .

Thanks to this paper, I have built my own orbital localizer, based on Pipek-Mezey and Lowdin population. It converges well in simple systems, but extremely slowly in largely conjugated ones. The test on linear C8H10 (four double bonds, B3LYP/6-31g* 5d, random unitary matrix as initial guess) shows that the cost function reaches around 17.6803 (the converged value should be 17.682253, given by Multiwfn) but does not increase much since then, although the maximal element of |G| is 0.00638, still far from the convergence threshold. The resulted non-converged orbitals have significant sigma-pi mixing, a phenomenon often seen in Foster-Boys localization.

Perhaps you have alleviated the problem in Erkale? Would you please share your solution to it? Thank you. (:D)

**Comment by susilehtola** [comment]
The problem is that the optimizer has no preconditioning. Preconditioning with a diagonal Hessian is straightforward, and the plan has been for a long time to write a generalized orbital optimizer that could also be used for orbital localization.

Does the calculation work in ERKALE? What's the geometry?

**Comment by FreemanTheMaverick** [comment]
> The problem is that the optimizer has no preconditioning. Preconditioning with a diagonal Hessian is straightforward, and the plan has been for a long time to write a generalized orbital optimizer that could also be used for orbital localization.
> 
> Does the calculation work in ERKALE? What's the geometry?

Second order optimization will definitely enhance the performance. But I have googled the keywords "unitary matrix optimization hessian/BFGS" and none of the information appears so understandable to me as your J. Chem. Theory Comput. 2013, 9, 12, 5365–5372. So I cannot do much about it.

It seems I have alleviate this problem a little bit. The key is starting from CMO multiplying a little random rotation. In CMO, sigma and pi are already seperated, so starting from CMO will prevent the orbitals from sigma-pi mixing. The little random rotation is to break the symmetry of CMO without losing the sigma-pi seperation feature. However, the optimization is still slow by the end, so I have to set the convergence threshold higher in practice.

I have not tried ERKALE. The geometry is as follows.
```
18
C8H10
 C                  0.13606400    4.31319100    0.00000000
 C                  0.65146200    3.07147000    0.00000000
 H                 -0.93833800    4.48327400    0.00000000
 H                  0.76944700    5.19485700    0.00000000
 H                  1.73483700    2.94638000    0.00000000
 C                 -0.13606400    1.85629300    0.00000000
 C                  0.38955300    0.60617900    0.00000000
 H                 -1.22063700    1.97325500    0.00000000
 H                  1.47481800    0.49397500    0.00000000
 C                 -0.38955300   -0.60617900    0.00000000
 C                  0.13606400   -1.85629300    0.00000000
 H                 -1.47481800   -0.49397500    0.00000000
 H                  1.22063700   -1.97325500    0.00000000
 C                 -0.65146200   -3.07147000    0.00000000
 C                 -0.13606400   -4.31319100    0.00000000
 H                 -1.73483700   -2.94638000    0.00000000
 H                 -0.76944700   -5.19485700    0.00000000
 H                  0.93833800   -4.48327400    0.00000000
```

**Comment by susilehtola** [comment]
False bug report.
